CREATE TABLE SPRING_MEMBER(
	 SMNUM VARCHAR2(20) PRIMARY KEY 
    ,SMID  VARCHAR2(20)
    ,SMPW  VARCHAR2(200)
	,SMNAME VARCHAR2(100)
	,SMADDR VARCHAR2(300)
	,SMPHOTO VARCHAR2(300)
	,SMDELYN VARCHAR2(1)
	,SMINSERTDATE DATE
	,SMUPDATEDATE DATE 
);

select * from spring_member