2021-01-06
<BOARD WEB>

CREATE TABLE BOARD(
     SEQ NUMBER(5) PRIMARY KEY
    ,TITLE VARCHAR2(200)
    ,WRITER VARCHAR2(20)
    ,CONTENTT VARCHAR2(2000)
    ,INSERTDATE DATE
    ,UPDATEDATE DATE
    ,CNT NUMBER(5)
);
SELECT * FROM BOARD;
